language: node_js
node_js: stable
install: npm install
before_script: npm install -g gulp-cli
script: gulp build
deploy:
  provider: pages
  local_dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
  target_branch: gh-pages
